name: wisecrop
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 4.1.3

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  retrofit: ^4.4.1
  dio: ^5.7.0
  webview_flutter: ^4.8.0
  percent_indicator: ^4.2.3
  cool_alert: ^2.0.1
  flutter_native_splash: ^2.4.1  # Splash screen dependency
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.0
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  pretty_dio_logger: ^1.4.0
  simple_fontellico_progress_dialog: ^0.3.0
  shared_preferences: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  firebase_messaging: ^15.1.3
  device_info_plus: ^10.1.2
  dart_jsonwebtoken: ^2.14.1
  flutter_local_notifications: ^17.2.3
  fl_country_code_picker: ^0.1.9+1
  flutter_inappwebview: ^6.0.0
  webview_flutter_web: ^0.2.3+2
  webview_flutter_platform_interface: ^2.10.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_gen_runner:
  retrofit_generator: ^6.0.0+1
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  built_value_generator: ^8.4.4

flutter_gen:
  output: lib/gen/  # Optional (default: lib/gen/)
  line_length: 80  # Optional (default: 80)
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

# flutter_native_splash configuration should be at the top level
flutter_native_splash:
  color: "#3aae68"  # Background color for splash screen
  image: "assets/images/wisecrop_logo_white.png"  # Path to your splash image
  android_12:
    color: "#3aae68"
  android: true
  ios: true
