// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAadWW-m-ibeIDoNG6LTr1CorvlqygITcI',
    appId: '1:603804644803:android:cb8aa29496253671f1b976',
    messagingSenderId: '603804644803',
    projectId: 'orbital-ego-539',
    databaseURL: 'https://orbital-ego-539.firebaseio.com',
    storageBucket: 'orbital-ego-539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUj0fymxp2CnnqgXLH3cXD_Uvl8Tbwpu0',
    appId: '1:603804644803:ios:84cb3a2d25093ad4f1b976',
    messagingSenderId: '603804644803',
    projectId: 'orbital-ego-539',
    databaseURL: 'https://orbital-ego-539.firebaseio.com',
    storageBucket: 'orbital-ego-539.appspot.com',
    androidClientId: '603804644803-b50rqbaefm00ci9mp53q8np6lrndk58p.apps.googleusercontent.com',
    iosClientId: '603804644803-ttte6u40p6e8kc8v0d3b22lh2079knuj.apps.googleusercontent.com',
    iosBundleId: 'com.app.Wisecrop',
  );

}